### PR TITLE
TG-127: Shared component: Dropdown

### PR DESCRIPTION
**Pull request by SuarezAlexisEzequiel**
Ticket items requested:
-Styles can be modified because we don't have design
-Hover on moving option
-Input size should be the same as input

How to add the component to your code succesfully:
1. Call the component into the file where you want to use it.
2. On apply complete the next params, with the corresponding information
- data: Here you put the fetched data of the entity to offer in the select.
- name: Here, as a String, the name that the input would carry is passed to recognize it in the assembly of the json for the submit.
- labelText: Here, they also place the content of the upper Label of the field in String.
- path: Here, they designate the specific param to show next to the ID in the dropdown, for example for employee, it would go "firstName", for task, "description" and so on.
- onChange: Here goes the update function by change event.

-14/06/2022- 

- Added feature to implement "active" Dropdown, only use params: {name, labelText, onChange}
- Added dropdown component into AddNew.js file on Projects to example for implementation
- Added an empty option outside the map, with the labelText as content

### CODE REVIEW

**Review by Juanoauil — APPROVED** [review]
dudoso

**Review by MartinDidoli — APPROVED** [review]
seems all good

**Review by gregorioelias — APPROVED** [review]
Looks nice.

**Comment by cocolobos** [comment]
Can we add an empty option outside the map "Select Project", "Select Employee" something like that to use it as placeholder

**Pull request merged**
