### PR TITLE
TG-145: Update sign up page Employee

### PR DESCRIPTION
**Pull request by SuarezAlexisEzequiel**
- Modified routes on Layout ('/employees/form' now is '/employee/signup')
- Modified title on FormEmployee.jsx
- Modified styles on employee,module.css
- Changed contain of button 'Add Employee' into 'Sign Up'

### CODE REVIEW

**Comment by cocolobos** [comment]
We need a button on the landing page to get to the form

**Comment by cocolobos** [comment]
After adding the button on the landing, we should remove the sign up button on the employee table

**Comment by cocolobos** [comment]
the Active dropdown should be center and the buttons should be separated from the dropdown

**Comment by cocolobos** [comment]
The sign up title should be upper above the logo

**Review by cocolobos — APPROVED** [review]

**Review by MartinDidoli — APPROVED** [review]
All seems good

**Review by JulianDeme — APPROVED** [review]

**Pull request merged**
